# Generated by Django 3.2.8 on 2021-10-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211009_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Critiques', 'verbose_name_plural': 'Liste des critiques'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Liste des cickets'},
        ),
    ]
