# Generated by Django 3.2.8 on 2021-10-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211009_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Liste des tickets'},
        ),
    ]
