# Generated by Django 3.2.8 on 2021-10-13 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211013_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 53, 39, 815411, tzinfo=utc)),
        ),
    ]
