# Generated by Django 3.2.8 on 2021-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='AA', max_length=150, verbose_name='Mot de passe'),
        ),
    ]
