# Generated by Django 3.2.8 on 2021-10-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'required': 'test', 'unique': 'aaaa'}, max_length=150, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
